=== Assayyaad/assayyaad.github.io/schemas/ar/certificates.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "certificates.schema.json",

  "title": "الشهادات",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "اسم الشهادة"
      },
      "id": {
        "type": "string",
        "description": "معرّف الشهادة"
      },
      "image": {
        "type": "string",
        "description": "رابط الصورة أو مسارها"
      },
      "link": {
        "type": "string",
        "format": "uri",
        "description": "رابط إلى الشهادة"
      },
      "provider": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "اسم الجهة المصدرة"
          },
          "link": {
            "type": "string",
            "format": "uri",
            "description": "رابط إلى الجهة المصدرة"
          },
          "icon": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:[-_][a-z0-9]+)*:[a-z0-9]+(?:[-_][a-z0-9]+)*$",
            "description": "معرّف Iconify صالح لجهة إصدار الشهادة"
          }
        },
        "required": ["name", "link", "icon"],
        "additionalProperties": false,
        "description": "معلومات الجهة المصدرة للشهادة"
      }
    },
    "required": ["name", "id", "image", "link", "provider"],
    "additionalProperties": false
  }
}

=== Assayyaad/assayyaad.github.io/ar/data/cv/pages/game-programmer/certificates.json
[
  {
    "name": "خوارزميات وهياكل بيانات JavaScript",
    "id": "",
    "image": "/img/cert/javascript-algorithms-and-data-structures.png",
    "link": "https://freecodecamp.org/certification/Assayyaad/javascript-algorithms-and-data-structures",
    "provider": {
      "name": "FreeCodeCamp",
      "link": "https://freecodecamp.org",
      "icon": "simple-icons:freecodecamp"
    }
  },
  {
    "name": "مقدمة في C#",
    "id": "CC-KQMDTAMA",
    "image": "/img/cert/introduction-to-csharp.png",
    "link": "https://www.sololearn.com/en/certificates/CC-KQMDTAMA",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "مقدمة في JavaScript",
    "id": "CC-7A1QGUWT",
    "image": "/img/cert/introduction-to-javascript.png",
    "link": "https://www.sololearn.com/en/certificates/CC-7A1QGUWT",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "مقدمة في C++",
    "id": "CT-DKF29HTQ",
    "image": "/img/cert/cplusplus.png",
    "link": "https://www.sololearn.com/en/certificates/CT-DKF29HTQ",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "التقنية للجميع",
    "id": "CC-49YAACNH",
    "image": "/img/cert/tech-for-everyone.png",
    "link": "https://api2.sololearn.com/v2/certificates/CC-49YAACNH/image/png",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  }
]

=== Assayyaad/assayyaad.github.io/en/data/cv/pages/game-programmer/certificates.json
[
  {
    "name": "JavaScript Algorithms and Data Structures",
    "id": "",
    "image": "/assets/cert/javascript-algorithms-and-data-structures.png",
    "link": "https://freecodecamp.org/certification/Assayyaad/javascript-algorithms-and-data-structures",
    "provider": {
      "name": "FreeCodeCamp",
      "link": "https://freecodecamp.org",
      "icon": "simple-icons:freecodecamp"
    }
  },
  {
    "name": "Introduction to C#",
    "id": "CC-KQMDTAMA",
    "image": "/assets/cert/introduction-to-csharp.png",
    "link": "https://www.sololearn.com/en/certificates/CC-KQMDTAMA",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "Introduction to JavaScript",
    "id": "CC-7A1QGUWT",
    "image": "/assets/cert/introduction-to-javascript.png",
    "link": "https://www.sololearn.com/en/certificates/CC-7A1QGUWT",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "Introduction to C++",
    "id": "CT-DKF29HTQ",
    "image": "/assets/cert/cplusplus.png",
    "link": "https://www.sololearn.com/en/certificates/CT-DKF29HTQ",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "Tech for Everyone",
    "id": "CC-49YAACNH",
    "image": "/assets/cert/tech-for-everyone.png",
    "link": "https://api2.sololearn.com/v2/certificates/CC-49YAACNH/image/png",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  }
]
